### ISSUE TITLE
A small error in Ubuntu 18.04 64bits.

### ISSUE THREAD

**Issue by pmasterBR** [Team-XLink/releases#2]
Thanks for update, but i have this little problem :

Config file: ./kaiengine.conf
Web interface is ready, connect to: http://127.0.0.1:34522/
Downloading language file en.xml
Initializing XLink Kai engine...

Downloading configuration... OK
Segmentation fault (core dumped)

This error occurs at the end : Segmentation fault (core dumped)

**Comment by CrunchBite** [comment]
Hmm that should have been fixed. What is the version string it printed out at the top?

**Comment by pmasterBR** [comment]
> Hmm that should have been fixed. What is the version string it printed out at the top?

Version of Kai ? : XLink Kai v7.4.37 build 539579348 Linux x86_64 (c) 2020 Team XLink  https://www.teamxlink.co.uk/

**Comment by hedgehog1029** [comment]
Also experiencing this segmentation fault, gdb doesn't have any useful information (symbols are stripped I suppose).

Here's my full stdout:
```
XLink Kai v7.4.37 build 539579348 Linux x86_64 (c) 2020 Team XLink  https://www.teamxlink.co.uk/

Config file: ./kaiengine.conf
Web interface is ready, connect to: http://127.0.0.1:34522/
Downloading language file en.xml
Initializing XLink Kai engine...

Downloading configuration... OK
Updating webui
[1]    310321 segmentation fault  ./kaiengine
```

**Comment by hedgehog1029** [comment]
It looks like this only occurs if you run the engine without sudo - even with CAP_NET_ADMIN applied.

**Comment by CrunchBite** [comment]
Ah, looks like I forgot to debug CAP_NET_ADMIN on 64bit systems. I'll try to find the problem and fix it for the next release.
Thanks for finding this!
